services:
  muto:
    tty: true
    build: .
    container_name: muto_container
    volumes:
      - .:/muto_ws
    ports:
      - "5678:5678"  # debugpy port
    command: /bin/sh -c "/muto_ws/bootstrap.sh && pip3 install debugpy"