services:
  muto:
    tty: true
    build: .
    container_name: muto_container
    ports:
      - "5678:5678"  # debugpy port
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/muto_ws:cached